spring.application.name=StageDesignerPro
server.port=8081

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/stagedesigner_db
spring.datasource.username=stage_user
spring.datasource.password=RfQvgp2VB13tKq9

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
